bibliotheque_index:
    path:     /
    defaults: { _controller: BibliothequeBundle:Bibliotheque:index }

bibliotheque_livres:
    path:     /livres
    defaults: { _controller: BibliothequeBundle:Bibliotheque:livres }

bibliotheque_panier:
    path:     /panier
    defaults: { _controller: BibliothequeBundle:Bibliotheque:panier }

bibliotheque_detail_livre:
    path:     /detail_livre/{titre}
    defaults: { _controller: BibliothequeBundle:Bibliotheque:detail_livre }

bibliotheque_detail_livre_par_theme:
    path:     /detail_theme/{theme}
    defaults: { _controller: BibliothequeBundle:Bibliotheque:detail_livre_par_theme }
