user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

bibliotheque:
    resource: "@BibliothequeBundle/Resources/config/routing.yml"
    prefix:   /

login:
   pattern:   /login
   defaults:  { _controller: UserBundle:Security:login }

login_check:
   pattern:   /login_check

logout:
  pattern:    /logout





admin:
  pattern:    /admin
  defaults:   { _controller: UserBundle:Security:admin }

bibliotheque_admin_livres:
  pattern:    /admin/livres
  defaults:   { _controller: UserBundle:Security:admin_livres }

bibliotheque_admin_prets:
  pattern:    /admin/prets
  defaults:   { _controller: UserBundle:Security:admin_prets }

bibliotheque_admin_ajout_user:
  pattern:    /admin/ajout_utilisateur
  defaults:   { _controller: UserBundle:Security:admin_ajout_user }

bibliotheque_admin_modif_user:
  pattern:    /admin/modif_utilisateur
  defaults:   { _controller: UserBundle:Security:admin_modif_user }

bibliotheque_admin_modif_user_form:
  path:       /admin/modif_utilisateur_form/{nom}
  defaults:   { _controller: UserBundle:Security:admin_modif_user_form }








bibliotheque_bibliothecaire:
  pattern:    /bibliothecaire
  defaults:   { _controller: UserBundle:Security:bibliothecaire }