user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

bibliotheque:
    resource: "@BibliothequeBundle/Resources/config/routing.yml"
    prefix:   /

login:
   pattern:   /login
   defaults:  { _controller: UserBundle:Security:login }

login_check:
   pattern:   /login_check

logout:
  pattern:    /logout




admin:
  pattern:    /admin
  defaults:   { _controller: UserBundle:Admin:admin }

bibliotheque_admin_prets:
  pattern:    /admin/prets
  defaults:   { _controller: UserBundle:Admin:admin_prets }

bibliotheque_admin_ajout_user:
  pattern:    /admin/ajout_utilisateur
  defaults:   { _controller: UserBundle:Admin:admin_ajout_user }

bibliotheque_admin_modif_user:
  pattern:    /admin/modif_utilisateur
  defaults:   { _controller: UserBundle:Admin:admin_modif_user }

bibliotheque_admin_modif_user_form:
  path:       /admin/modif_utilisateur_form/{nom}
  defaults:   { _controller: UserBundle:Admin:admin_modif_user_form }

bibliotheque_admin_suppr_user:
  pattern:    /admin/suppr_utilisateur
  defaults:   { _controller: UserBundle:Admin:admin_suppr_user }

bibliotheque_admin_suppr_user_form:
  path:       /admin/suppr_utilisateur_form/{nom}
  defaults:   { _controller: UserBundle:Admin:admin_suppr_user_form }

bibliotheque_admin_ajout_livre:
  pattern:    /admin/ajout_livre
  defaults:   { _controller: UserBundle:Admin:admin_ajout_livre }

bibliotheque_admin_modif_livre:
  pattern:    /admin/modif_livre
  defaults:   { _controller: UserBundle:Admin:admin_modif_livre }

bibliotheque_admin_modif_livre_form:
  pattern:    /admin/modif_livre_form/{nom}
  defaults:   { _controller: UserBundle:Admin:admin_modif_livre_form }

bibliotheque_admin_suppr_livre:
  pattern:    /admin/admin_suppr_livre
  defaults:   { _controller: UserBundle:Admin:admin_suppr_livre }

bibliotheque_admin_suppr_livre_form:
  pattern:    /admin/admin_suppr_livre_form/{nom}
  defaults:   { _controller: UserBundle:Admin:admin_suppr_livre_form }

bibliotheque_admin_ajout_exemplaire:
  pattern:    /admin/admin_ajout_exemplaire
  defaults:   { _controller: UserBundle:Admin:admin_ajout_exemplaire }

bibliotheque_admin_ajout_exemplaire_form:
  pattern:    /admin/admin_ajout_exemplaire_form/{isbn}
  defaults:   { _controller: UserBundle:Admin:admin_ajout_exemplaire_form }

bibliotheque_admin_ajout_auteur:
  pattern:    /admin/ajout_auteur
  defaults:   { _controller: UserBundle:Admin:admin_ajout_auteur }

bibliotheque_admin_suppr_auteur:
  pattern:    /admin/suppr_auteur
  defaults:   { _controller: UserBundle:Admin:admin_suppr_auteur }

bibliotheque_admin_ajout_editeur:
  pattern:    /admin/ajout_editeur
  defaults:   { _controller: UserBundle:Admin:admin_ajout_editeur }

bibliotheque_admin_ajout_theme:
  pattern:    /admin/ajout_theme
  defaults:   { _controller: UserBundle:Admin:admin_ajout_theme }

bibliotheque_admin_suppr_theme:
  pattern:     /admin/suppr_theme
  defaults:    { _controller: UserBundle:Admin:admin_suppr_theme }






bibliotheque_bibliothecaire:
  pattern:    /bibliothecaire
  defaults:   { _controller: UserBundle:Bibliothecaire:bibliothecaire }






bibliotheque_profil:
  path:     /profil
  defaults: { _controller: UserBundle:Security:profil }

profil_info:
  path:     /profil_info/{username}
  defaults: { _controller: UserBundle:Security:profil_info }

Bibliotheque_contact:
  path:    /contact
  defaults: { _controller: UserBundle:Security:contact}
  requirements:
        _method:  GET|POST
