security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Bibliotheque\UserBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:           ROLE_ADMIN
        ROLE_BIBLIOTEQUAIRE:  ROLE_BIBLIOTHECAIRE
        ROLE_ETUDIANT:        ROLE_ETUDIANT
        ROLE_PROFESSEUR:      ROLE_PROFESSEUR

    providers:
        main:
            entity: { class: Bibliotheque\UserBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                 login_path:  login
                 check_path:  login_check
                 remember_me: true
                 success_handler: RedirectionApresLogin
            logout:
                 path: logout
                 target: /
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/bibliothecaire, roles: ROLE_BIBLIOTEQUAIRE }
        - { path: ^/utilisateur, roles: ROLE_PROFESSEUR ROLE_ETUDIANT }