<?php

namespace Bibliotheque\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EditeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EditeurRepository extends EntityRepository
{
	public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT nom FROM UserBundle:Editeur nom ORDER BY nom.nom ASC'
            )
            ->getResult();
    }
}
