<?php

namespace Bibliotheque\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * livresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class livresRepository extends EntityRepository
{
}
