<?php

namespace Bibliotheque\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LivresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivresRepository extends EntityRepository
{
}
